"""Dependency-only runtime contract mirrored from HA-MCP master."""

from .contract import (
    HA_MCP_COMPONENT_REQUIREMENTS,
    HA_MCP_COMPONENT_VERSION,
    HA_MCP_FASTMCP_MODULE,
    HA_MCP_FASTMCP_VERSION,
    HA_MCP_MASTER_SHA,
    HA_MCP_REPOSITORY,
    HA_MCP_RUNTIME_CONTRACT_ID,
    HA_MCP_RUNTIME_REQUIREMENT,
    HA_MCP_SERVER_REQUIREMENTS,
    HA_MCP_SERVER_VERSION,
    HA_MCP_VENDOR_HASHES,
)

__all__ = (
    "HA_MCP_COMPONENT_REQUIREMENTS",
    "HA_MCP_COMPONENT_VERSION",
    "HA_MCP_FASTMCP_MODULE",
    "HA_MCP_FASTMCP_VERSION",
    "HA_MCP_RUNTIME_REQUIREMENT",
    "HA_MCP_VENDOR_HASHES",
    "HA_MCP_MASTER_SHA",
    "HA_MCP_REPOSITORY",
    "HA_MCP_RUNTIME_CONTRACT_ID",
    "HA_MCP_SERVER_REQUIREMENTS",
    "HA_MCP_SERVER_VERSION",
)
