"""Generated dependency contract for one immutable HA-MCP master snapshot.

Do not edit this file by hand. Run scripts/sync_ha_mcp_runtime_contract.py
to refresh both the server and custom-component sides from the same commit.
Only dependency metadata is mirrored; no HA-MCP server or tool code is bundled.
"""

HA_MCP_REPOSITORY = "homeassistant-ai/ha-mcp"
# renovate: datasource=git-refs packageName=https://github.com/homeassistant-ai/ha-mcp branch=master
HA_MCP_MASTER_SHA = "ad122e4787ab2a184e8140fb2fe30a70b1e38306"
HA_MCP_SERVER_VERSION = "8.4.0"
HA_MCP_COMPONENT_VERSION = "2.1.0"

HA_MCP_SERVER_REQUIREMENTS = (
    "fastmcp==3.4.7",
    "httpx[socks]==0.28.1",
    "pydantic==2.13.4",
    "python-dotenv==1.2.3",
    "truststore==0.10.4",
    "cryptography>=48.0.0,<51",
    "pydantic-monty==0.0.18",
    "tzdata>=2024.1",
    "packaging>=24.0",
)

HA_MCP_COMPONENT_REQUIREMENTS = ("ruamel.yaml>=0.18.0",)

HA_MCP_FASTMCP_REQUIREMENT = "fastmcp==3.4.7"
HA_MCP_RUNTIME_CONTRACT_ID = f"{HA_MCP_REPOSITORY}@{HA_MCP_MASTER_SHA}"
